### ISSUE TITLE
IN, BE: Reviews + Requests Model + API

### ISSUE THREAD

**Issue by bonnieli** [hatchways/team-acorn#2]
- Create a document high level on how reviews and requests will work
    - user requests a review, they get matched with someone
    - requested reviewer can decline (or it times out)
    - if they decline, new request is sent (requests need to know who has already declined)
- Create the reviews model to store title, user + messages
- Create a requests model that is linked to a review and a user
    - Will probably also need statuses 
- API that creates a review and subsequently, creates request that is pending (POST)
- When you click upload code, a pending review is created 
- API to get all your created reviews (GET)

**Comment by skassam21** [comment]
### How will this work?

A user will request someone to review their code (using the code upload dialog)
Create a pending request object in the back-end (You need to write this API request)

Using task queues (look up), we are going to enqueue a task to find a user to review the request 
If no appropriate user is found, we need to enqueue a future task (one day later) to again find a user for the task
Once we found a user, we would update them as a reviewer 

That user will be able to accept / reject a request - if they reject it, we need to enqueue to find a new user

**Comment by skassam21** [comment]
### How to find users
- based on their language level
- has this user declined this request before? (need to store this information)
- favour candidates with less pending reviews
